# Generated by Django 3.0.5 on 2020-04-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='name')),
                ('last_name', models.CharField(max_length=35)),
            ],
        ),
    ]
