# Generated by Django 2.2.10 on 2020-06-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point_of_care', '0003_intervention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intervention',
            options={'ordering': ['short_description']},
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='notes',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='intervention',
            new_name='short_description',
        ),
    ]
