# Generated by Django 2.2.10 on 2020-06-01 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('point_of_care', '0004_auto_20200601_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('intervention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_care.Intervention')),
                ('resident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='point_of_care.Resident')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
